<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>0.1.0-preview.1</Version>
  </PropertyGroup>
</Project>